import { Inter } from "next/font/google";
import "./globals.css";
import { Toaster } from "react-hot-toast";
import { UserProvider } from "@auth0/nextjs-auth0/client";
import Layout from "../components/Layout";
import ApolloProviders from "@/components/ApolloProviders";
import { InjuryProvider } from "@/context/BodyMapContext";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <UserProvider>
        <body className={inter.className}>
          <ApolloProviders>
            <InjuryProvider>
              <Layout>
                <Toaster position="top-right" />
                {children}
              </Layout>
            </InjuryProvider>
          </ApolloProviders>
        </body>
      </UserProvider>
    </html>
  );
}
