import { Inter } from "next/font/google";
import "./globals.css";
import { UserProvider } from "@auth0/nextjs-auth0/client";
import ApolloProviders from "@/components/context/ApolloProviders";
import { InjuryProvider } from "@/components/context/BodyMapContext";
import Layout from "@/components/Layout";
import { Toaster } from "react-hot-toast";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <UserProvider>
        <ApolloProviders>
          <body className={inter.className}>
            <InjuryProvider>
              <Toaster position="top-right" />
              <Layout>{children}</Layout>
            </InjuryProvider>
          </body>
        </ApolloProviders>
      </UserProvider>
    </html>
  );
}
